apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: immich-cnpg-pod-monitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      postgresql: immich-postgres
  podMetricsEndpoints:
  - port: metrics
