apiVersion: v1
kind: Secret
stringData:
    DB_USERNAME: ENC[AES256_GCM,data:IXrlZOK+,iv:I0QoM7mNRb7k4lt5bqhR4cE4xqHj1QEbmMr7NvztRdM=,tag:/rB8m3sR0RMmWP+abCAeUw==,type:str]
    DB_DATABASE_NAME: ENC[AES256_GCM,data:Ox5m7LQ/,iv:RatpTb8PvdzSkG83FaN8tobsBNYF78hqcmGfFlP9W58=,tag:k9l0Yqe9lLppleoqGvjWwQ==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:o+WrWPGD7J2kYF2krzurBvjcnUGfHFaBISMsvWwCRPN4Ao3vR9WtkA==,iv:RiYpxgZ9AgGvWUcuVYAIXLJkIWdrkA1DWVA/XLdJv64=,tag:VwK0fbE1Tyyh7Cct28Fvuw==,type:str]
    username: ENC[AES256_GCM,data:NkBJxKcF,iv:O2SSykDSVk9Nm5mYJtk8s2ce5T8I5Q8jWar28YQroYc=,tag:kFRZrPN7PHKd9tUEfw/WEQ==,type:str]
    password: ENC[AES256_GCM,data:i6bOMiCQqZSmKHsanhOa0yMUCkA2D8MlQt5aZMDD0zLWcyRI7ia7aw==,iv:C/4Sq7jYa6rvi+ePh/D868R8KhSmu8riWARupx4jf7o=,tag:lMlK1piIehJVYiyEJxbnyg==,type:str]
metadata:
    name: immich-postgres-user
    namespace: immich
type: kubernetes.io/basic-auth
sops:
    age:
        - recipient: age1x063t8d3lk76x44np5jq8rqpr4q740825xyh0xxwq5rh68wz5cvsul93vm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGUTZDMXYyU2hGKzMxNDFN
            Z3ExQ2twem1jaTAxYWtLRHdqdXVqSy9CaWdjCi9mWFRhNnpPU01ETU85d0VSQXpM
            TkhQK2VGOThUclY2Zm1jT09ZWUptNm8KLS0tIGVtUEJJOTJvRkFJcUk1SWxBUUxL
            bG1JeFRtTFJzcnJtRHE4WHJhRFBrN28KACCNzc7cGjyjOln2dYq1EL+fQHsPPRPv
            cNGxjwgdazbitfKj0jYybt72ev8uCiTqYyvKXQ04gb9iKjorvI5cwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-09T17:24:13Z"
    mac: ENC[AES256_GCM,data:LydbjvuTrE464ZHeDtBWEYjnwLC5dIM9PBT4i050AFbZTuT+ufnrvzNSz6RX8Qxtv8v0/W3fcozAS4EpBIsLW1TF6xUL+bo1W+ASF+EHHwwuH/gjXPUiNLAHpIaYX9tIrX1SypLUjEaWxfdTyn3dxGWgomCkCqaeAAXEZ377ea8=,iv:HqDqWzcp64lMu5+pjhF8DLITDokBX1islNmEECSGMJc=,tag:LIUWzCjvq6pziFhR4JRiyw==,type:str]
    encrypted_regex: ^(data|stringData|secret|secureJsonData)$
    version: 3.11.0
