apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: immich_dependencies
namespace: immich
resources:
  - ./immich-podMonitor.yaml
  - ./immich-cnpg-cluster.yaml
spec:
  dependsOn:
    - name: prometheus
    - name: cnpg
