apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: immich
resources:
  - ./immich-pvc-photos.yaml
  - ./immich-cnpg-cluster.yaml
  - ./immich-cnpg-secrets.enc.yaml
  - ../../base/immich
patches:
  - path: immich-patch.yaml
    target:
      kind: HelmRelease
