apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: immich
namespace: immich
resources:
  - ../../base/immich
  - ./immich-cnpg-secrets.enc.yaml
  - ./immich-podMonitor.yaml
  - ./immich-cnpg-cluster.yaml
  - ./immich-pvc-photos.yaml
patches:
  - path: immich-patch.yaml
    target:
      kind: HelmRelease
