---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  chart:
    spec:
      version: ">=1.19.1"
  values:
    crds:
      enabled: true
    prometheus:
      servicemonitor:
        enabled: true
    webhook:
      serviceLabels:
        release: prometheus
    cainjector:
      serviceLabels:
        release: prometheus
