---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus
  namespace: prometheus
spec:
  chart:
    spec:
      version: ">=79.4.1"
  values:
    grafana:
      adminUser:
        valueFrom:
          secretKeyRef:
            name: prometheus-grafana-admin-user
            key: user
      adminPassword:
        valueFrom:
          secretKeyRef:
            name: prometheus-grafana-admin-user
            key: password
      ingress:
        enabled: true
        hosts:
          - grafana.home.local
        path: /
