---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: prometheus
spec:
  chart:
    spec:
      version: ">=79.4.1"
  values:
    grafana:
      ingress:
        enabled: true
        hosts:
          - host: grafana.home.local
            paths:
            - path: "/"
