apiVersion: v1
kind: Namespace
metadata:
  name: longhorn-system
  labels:
    toolkit.fluxcd.io/tenant: dev-team
    # Necessary to allow necessary pod communication in Talos
    pod-security.kubernetes.io/enforce: privileged
