apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: technitium-dnsserver
resources:
  - ../../base/technitium-dnsserver
patches:
  - path: technitium-dnsserver-patch.yaml
    target:
      kind: HelmRelease
