---
apiVersion: "openebs.io/v1beta3"
kind: DiskPool
metadata:
  name: staging-cp-0-pool
  namespace: openebs
spec:
  node: staging-cp-0
  disks: ["aio:///dev/disk/by-path/virtio-pci-0000:00:0b.0"]
---
apiVersion: "openebs.io/v1beta3"
kind: DiskPool
metadata:
  name: staging-worker-0-pool
  namespace: openebs
spec:
  node: staging-worker-0
  disks: ["aio:///dev/disk/by-path/virtio-pci-0000:00:0b.0"]
---
apiVersion: "openebs.io/v1beta3"
kind: DiskPool
metadata:
  name: staging-worker-1-pool
  namespace: openebs
spec:
  node: staging-worker-1
  disks: ["aio:///dev/disk/by-path/virtio-pci-0000:00:0b.0"]
