# One diskpool per node. Minimum of three (equal to IO engine count) to allow for replication factor of 3.
---
apiVersion: "openebs.io/v1beta3"
kind: DiskPool
metadata:
  name: staging-cp-0-pool
  namespace: openebs
spec:
  node: staging-cp-0
  # talosctl -n <node> get disk vdb -o yaml
  # Check symlinks. Using just /dev/vdb will not work.
  disks: ["aio:///dev/disk/by-path/virtio-pci-0000:00:0b.0"]
---
apiVersion: "openebs.io/v1beta3"
kind: DiskPool
metadata:
  name: staging-worker-0-pool
  namespace: openebs
spec:
  node: staging-worker-0
  # talosctl -n <node> get disk vdb -o yaml
  # Check symlinks. Using just /dev/vdb will not work.
  disks: ["aio:///dev/disk/by-path/virtio-pci-0000:00:0b.0"]
---
apiVersion: "openebs.io/v1beta3"
kind: DiskPool
metadata:
  name: staging-worker-1-pool
  namespace: openebs
spec:
  node: staging-worker-1
  # talosctl -n <node> get disk vdb -o yaml
  # Check symlinks. Using just /dev/vdb will not work.
  disks: ["aio:///dev/disk/by-path/virtio-pci-0000:00:0b.0"]
