apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openebs-repo
  namespace: openebs
spec:
  releaseName: openebs
  chart:
    spec:
      chart: openebs
      sourceRef:
        kind: HelmRepository
        name: openebs
  interval: 1m
  install:
    remediation:
      retries: 3
  # Default values
  values:
    ingress:
      main:
        enabled: true
