---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudnative-pg-release
  namespace: cloudnative-pg
spec:
  chart:
    spec:
      version: ">=0.26.1"
  values:
    ingress:
      enabled: true
      host: cloudnative-pg.home.local
      paths:
      path: /
      pathType: Prefix
