---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus
  namespace: prometheus
spec:
  timeout: 15m
  install:
    timeout: 15m
  chart:
    spec:
      version: ">=79.4.1"
  values:
    grafana:
      readinessProbe:
        initialDelaySeconds: 60
        periodSeconds: 10
        timeoutSeconds: 5
        failureThreshold: 10  # More lenient
      livenessProbe:
        initialDelaySeconds: 60
        periodSeconds: 10
        timeoutSeconds: 5
        failureThreshold: 10
      admin:
        existingSecret: "prometheus-grafana-admin-user"
        userKey: user
        passwordKey: password
      ingress:
        enabled: true
        hosts:
          - grafana.home.local
        path: /
