apiVersion: v1
kind: Secret
stringData:
    user: ENC[AES256_GCM,data:D0Akgqg=,iv:qk5LQdpe18osaczb6iOk4cFgm2qt+l/D7uAZaO6xOjs=,tag:7IXvxEXCotR4/H3Z0P3aRg==,type:str]
    password: ENC[AES256_GCM,data:fQNDfryc2pZAM3PPvm8SSPhUvqx9hWHhs2bfFF5iy0XnufNB12VVlw==,iv:qHVqH3jORVjC5zAD9NMjmqly2+B1DEyv8whQEZE4z+M=,tag:cq5iwELPYWRYFRb6QuMm6Q==,type:str]
metadata:
    name: prometheus-grafana-admin-user
    namespace: prometheus
type: kubernetes.io/basic-auth
sops:
    age:
        - recipient: age1x063t8d3lk76x44np5jq8rqpr4q740825xyh0xxwq5rh68wz5cvsul93vm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGUTZDMXYyU2hGKzMxNDFN
            Z3ExQ2twem1jaTAxYWtLRHdqdXVqSy9CaWdjCi9mWFRhNnpPU01ETU85d0VSQXpM
            TkhQK2VGOThUclY2Zm1jT09ZWUptNm8KLS0tIGVtUEJJOTJvRkFJcUk1SWxBUUxL
            bG1JeFRtTFJzcnJtRHE4WHJhRFBrN28KACCNzc7cGjyjOln2dYq1EL+fQHsPPRPv
            cNGxjwgdazbitfKj0jYybt72ev8uCiTqYyvKXQ04gb9iKjorvI5cwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-11T13:18:55Z"
    mac: ENC[AES256_GCM,data:AlznDB7Vr1bd3Xv7SAJ2ZqoDcL89YRebMzfxoKOZaxUuWO6a/2I4UW2wm8WfY4bQmBe/J7tKA/xRsjEJbsLYbX6eF1euMQvjgLyhx7zJvEUSLcrjNMslLDCIt7IWcH6jTHB6fA2oEh0im8dUJ9wDjyY/kNVxC1nZsaVhQRaGE3s=,iv:5t4mGJnpMOgyNsH/LUKT1p9UEPJg6uDzpo6C+jrKFs0=,tag:pgAZVpTgPdRD+Klad55HAw==,type:str]
    encrypted_regex: ^(data|stringData|secret|secureJsonData)$
    version: 3.11.0
